version: '3.8'

services:
  php:
    image: ariimam/mazer-php:v1
    ports:
      - "9000:9000"
    networks:
      - laravelss
  nginx:
    image: ariimam/mazer-web:v1
    ports:
      - "80:80"
    networks:
      - laravelss
    depends_on:
      - php
  mysql:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    networks:
      - laravelss
    environment:
      MYSQL_DATABASE: laravel
    #   MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    #   MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

networks:
  laravelss:
